### ISSUE TITLE
[Epic] Makefile generation improvements

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/ci-mgmt#202]
- [ ] Use file targets (see [awsx Makefile](https://github.com/pulumi/pulumi-awsx/blob/master/Makefile) for reference). This should allow local development loops to be faster.
- [ ] Generalise the makefile options to not assume providers are owned by Pulumi.
- [ ] Add provider shim mods target (i.e. run `go mod tidy` in a target)
- [ ] Make `provider-ci` consumable externally – something like `npx pulumi-gen-build`
