### ISSUE TITLE
Bridge Update Papercuts 10/02/23

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/ci-mgmt#646]
During ops, we ran a bridge release and updated the bridge to all providers. Some updates were successful; others failed.

These are sorted by category and linked to the successful PR or failed Workflows. 

## Author Identity Unknown

This is a very frustrating occurrence where git cannot determine the identity of the runner in question.
Here's the issue for that: https://github.com/pulumi/upgrade-provider/issues/144

- [ ] aws - Author identity unknown: https://github.com/pulumi/pulumi-aws/actions/runs/6387505142/job/17335943737#step:3:1487
- [x] gcp - Author identity unknown: https://github.com/pulumi/pulumi-gcp/actions/runs/6387531061/job/17336012024#step:3:1240
- [x] azuread - Author identity unknown: https://github.com/pulumi/pulumi-azuread/actions/runs/6387507006/job/17335949495#step:3:993
- [x] artifactory - Author identity unknown: https://github.com/pulumi/pulumi-artifactory/actions/runs/6387502698/job/17335937010#step:3:905
- [ ] akamai - Author identity unknown: https://github.com/pulumi/pulumi-akamai/actions/runs/6387499107/job/17335926372#step:3:860
- [ ] confluentcloud - Author identity unknown: https://github.com/pulumi/pulumi-confluentcloud/actions/runs/6387514022/job/17335967429#step:3:859
- [ ] consul - Author identity unknown: https://github.com/pulumi/pulumi-consul/actions/runs/6387515397/job/17335971334#step:3:856
- [x] databricks - Author identity unknown: https://github.com/pulumi/pulumi-databricks/actions/runs/6387517179/job/17335975505#step:3:856
- [ ] digitalocean - Author identity unknown: https://github.com/pulumi/pulumi-digitalocean/actions/runs/6387519955/job/17335982486#step:3:939
- [ ] f5bigip - Author identity unknown: https://github.com/pulumi/pulumi-f5bigip/actions/runs/6387528602/job/17336005355#step:3:880
- [ ] gitlab - Author identity unknown: https://github.com/pulumi/pulumi-gitlab/actions/runs/6387533580/job/17336018063#step:3:950
- [x] hcloud Author identity unknown: https://github.com/pulumi/pulumi-hcloud/actions/runs/6387534715/job/17336020835#step:3:873
- [ ] local Author identity unknown: https://github.com/pulumi/pulumi-local/actions/runs/6387544229/job/17336043004#step:3:684
- [x] pagerduty Author identity unknown: https://github.com/pulumi/pulumi-pagerduty/actions/runs/6387563739/job/17336090973#step:3:858
- [ ] random - Author identity unknown: https://github.com/pulumi/pulumi-random/actions/runs/6387571150/job/17336109875#step:3:970
- [ ] splunk - Author identity unknown: https://github.com/pulumi/pulumi-splunk/actions/runs/6387581463/job/17336136599#step:3:818
- [ ] mysql - Author identity unknown: https://github.com/pulumi/pulumi-mysql/actions/runs/6387549497/job/17336055127#step:3:792

## No space left on device/ Runner received shutdown signal

Unsure if these are the same cause, but they're in a similar space.

- [ ] azure - No space left on device (github runner) https://github.com/pulumi/pulumi-azure/actions/runs/6387505876
- [ ] datadog - Runner received shutdown signal https://github.com/pulumi/pulumi-datadog/actions/runs/6387518686
- [x] oci Runner shut down https://github.com/pulumi/pulumi-oci/actions/runs/6387555747/job/17336069503

## `make upstream` failure

Filed in https://github.com/pulumi/upgrade-provider/issues/172

- [ ] auth0 - `make upstream` failure: https://github.com/pulumi/pulumi-auth0/actions/runs/6387504018/job/17335940476
- [ ] external - `make upstream` failure: https://github.com/pulumi/pulumi-external/actions/runs/6387527214/job/17336002314#step:3:1178

## Dirty Worktree

Not all of these have a similar diff!

- [ ] ec - PR failing with dirty worktree: https://github.com/pulumi/pulumi-ec/actions/runs/6387566744/job/17336172052?pr=154
- [ ] keycloak Dirty worktree in PR https://github.com/pulumi/pulumi-keycloak/actions/runs/6387584570/job/17336224131?pr=276
- [ ] kong Dirty worktree in PR https://github.com/pulumi/pulumi-kong/actions/runs/6387587213/job/17336223423?pr=213
- [x] newrelic - dirty worktree on PR: https://github.com/pulumi/pulumi-newrelic/actions/runs/6387602019/job/17336250903?pr=514
- [x] rabbitmq dirty worktree on PR: https://github.com/pulumi/pulumi-rabbitmq/actions/runs/6387604327/job/17336290791?pr=190
- [x] sumologic - dirty worktree with a _dotnet logo diff???_ https://github.com/pulumi/pulumi-sumologic/actions/runs/6387646681/job/17336401366?pr=169#step:19:49
- [x] vsphere - dirty worktree failure, seems related to wheels https://github.com/pulumi/pulumi-vsphere/actions/runs/6387634885/job/17336384057?pr=328
- [x] cloudflare Dirty Worktree on PR: https://github.com/pulumi/pulumi-cloudflare/actions/runs/6387559200/job/17336159829?pr=503

## Grab Bag

These all warrant more investigation on the provider

- [ ] azuredevops - this provider did not receive an upgrade-bridge Workflow at all
- [ ] docker - Failing lint and failing tests on PR: https://github.com/pulumi/pulumi-docker/actions/runs/6387560829/job/17336274461?pr=773
- [x] venafi - PR open, with unrelated longstanding test failures: https://github.com/pulumi/pulumi-venafi/actions/runs/6387627243/job/17336377934?pr=181

## Merged After Rerun due to flaky python deps install

Issue for this in #650

- [x] mongodbatlas - python deps install failure on PR, rerun: https://github.com/pulumi/pulumi-mongodbatlas/actions/runs/6387600977?pr=290 - UPDATE: [merged](https://github.com/pulumi/pulumi-mongodbatlas/pull/290)
- [x] openstack - flaky Python deps, trigger rerun: https://github.com/pulumi/pulumi-openstack/actions/runs/6387606471?pr=398 UPDATE [merged](https://github.com/pulumi/pulumi-openstack/pull/398)
- [x] tailscale failure to install python deps on PR tests; rerun https://github.com/pulumi/pulumi-tailscale/actions/runs/6387645772?pr=226 UPDATE: PR needed rebase
- [x] signalfx - failure to install Python deps on PR; triggered a rerun: https://github.com/pulumi/pulumi-signalfx/actions/runs/6387610874?pr=309 UPDATE [merged](https://github.com/pulumi/pulumi-signalfx/pull/309)
- [x] slack - flaky python deps install on PR tests; rerun https://github.com/pulumi/pulumi-slack/actions/runs/6387634352?pr=145 UPDATE [merged](https://github.com/pulumi/pulumi-slack/pull/145)
- [x] snowflake failure to install Python deps on PR; rerunning: https://github.com/pulumi/pulumi-snowflake/actions/runs/6387634581?pr=343 UPDATE: [merged](https://github.com/pulumi/pulumi-snowflake/pull/343)

### Merged After A Third Rerun due to failure on setup script

- [x] rancher2 - Python deps install failure on PR tests; rerun https://github.com/pulumi/pulumi-rancher2/actions/runs/6387641696?pr=272 UPDATE: Failure on setup script https://github.com/pulumi/pulumi-rancher2/actions/runs/6387641696/job/17370496012?pr=272; rerun: https://github.com/pulumi/pulumi-rancher2/actions/runs/6387641696?pr=272 UPDATE [merged](https://github.com/pulumi/pulumi-rancher2/pull/272) after two reruns

## Merged After Rerun due to a 502 on install-pulumi-cli

Issue for this in #652

- [x] libvirt - on PR, pulumi/action-install-pulumi-cli@v2 had a bad gateway? Re-running tests: https://github.com/pulumi/pulumi-libvirt/actions/runs/6387578369?pr=142 - UPDATE: [merged](https://github.com/pulumi/pulumi-libvirt/pull/142)
- [x] wavefront - 502 error on installing pulumi/action-install-pulumi-cli@v2 in PR tests; rerunning jobs https://github.com/pulumi/pulumi-wavefront/actions/runs/6387633615?pr=220 UPDATE: [merged](https://github.com/pulumi/pulumi-wavefront/pull/220)

## Merged 

I believe a human manually merged all these.

- [x] aiven - [merged](https://github.com/pulumi/pulumi-aiven/pull/378)
- [x] alicloud [merged](https://github.com/pulumi/pulumi-alicloud/pull/463)
- [x] archive - merged
- [x] civo [merged](https://github.com/pulumi/pulumi-civo/pull/287)
- [x] cloudamqp [merged](https://github.com/pulumi/pulumi-cloudamqp/pull/271)
- [x] cloudinit - merged https://github.com/pulumi/pulumi-cloudinit/pull/130
- [x] dnsimple - merged 😀 
- [x] equinix-metal [merged](https://github.com/pulumi/pulumi-equinix-metal/pull/129)
- [x] fastly [merged](https://github.com/pulumi/pulumi-fastly/pull/333)
- [x] github [merged](https://github.com/pulumi/pulumi-github/pull/462)
- [x] http [merged](https://github.com/pulumi/pulumi-http/pull/22)
- [x] kafka [merged](https://github.com/pulumi/pulumi-kafka/pull/228)
- [x] linode [merged](https://github.com/pulumi/pulumi-linode/pull/367)
- [x] mailgun [merged](https://github.com/pulumi/pulumi-mailgun/pull/194)
- [x] minio [merged](https://github.com/pulumi/pulumi-minio/pull/177)
- [x] nomad [merged](https://github.com/pulumi/pulumi-nomad/pull/125)
- [x] ns1 [merged](https://github.com/pulumi/pulumi-ns1/pull/244)
- [x] null [merged](https://github.com/pulumi/pulumi-null/pull/23)
- [x] okta merged 😀
- [x] onelogin [merged](https://github.com/pulumi/pulumi-onelogin/pull/136)
- [x] opsgenie [merged](https://github.com/pulumi/pulumi-opsgenie/pull/197)
- [x] postgresql [merged](https://github.com/pulumi/pulumi-postgresql/pull/277)
- [x] rke [merged](https://github.com/pulumi/pulumi-rke/pull/156)
- [x] spotinst [merged](https://github.com/pulumi/pulumi-spotinst/pull/428)
- [x] tls [merged](https://github.com/pulumi/pulumi-tls/pull/286)

# Summary

- 25 merged, manually, with no issue
- 9 merged after re-kicking flaky tests

- 9 dirty work trees
- 2 failure to find upstream go.mod
- 3 runners struggling with the workload
- 17 failed with git not accepting the identity of the runner attempting to open a PR
- 3 triggered genuine breaking tests

**Comment by t0yv0** [comment]
A lot of these fail because workflows are not merging. You wouldn't get newrelic to fail if https://github.com/pulumi/pulumi-newrelic/pull/517 merged for example, but it's not auto merging. I think @mjeffryes was looking into making sure all workflows auto merge.

**Comment by guineveresaenger** [comment]
I think we can close this issue as we have a release playbook and tooling: https://github.com/pulumi/platform-providers-team/blob/main/playbooks/Release%3A%20Terraform%20Bridge.md
